In [1]:
import numpy as np
from sklearn.datasets import load_diabetes

In [2]:
diabetes = load_diabetes()

In [93]:
X = diabetes.data
y = diabetes.target

In [97]:
class LassoRegression():
    
    def __init__(self, n_iter=500, alpha=1):
        self.n_iter = 500
        self.alpha  = 1
        
    def compute_rho(self, X, y, col_idx):
        pred   = self.predict(X)
        errors = y - pred
        rho    = X[:, col_idx] @ (errors + self.coef_[col_idx]*X[:, col_idx])
        return rho
    
    def predict(self, X):
        return X @ self.coef_
    
    def compute_zeta(self, X, col_idx):
        return  1 / np.sum(X[:, col_idx]**2)
    
    def soft_threshold(self, rho, alpha):
        if rho < -alpha:
            return rho + alpha
        elif rho >= -alpha and rho <= alpha:
            return 0
        else:
            return rho - alpha
        
    def fit(self, X, y):
        X           = np.insert(X, 0, 1, axis=1)
        self.coef_  = np.random.normal(loc=0.0, scale=0.1, size=X.shape[1])
        
        for _ in range(self.n_iter):
            for col in range(len(self.coef_)):
                rho  = self.compute_rho(X, y, col)
                zeta = self.compute_zeta(X, col) 
                if col is 0:
                    self.coef_[col] = rho
                else:
                    self.coef_[col] = zeta * self.soft_threshold(rho, self.alpha)

In [110]:
lasso = LassoRegression(alpha=1000)

In [111]:
lasso.fit(X, y)

In [112]:
X.shape

(442, 10)

In [113]:
lasso.coef_

array([ 6.72430000e+04, -7.72195148e+00, -2.37744411e+02,  5.20783128e+02,
        3.22221803e+02, -6.30532698e+02,  3.52395698e+02,  2.39068578e+01,
        1.48663188e+02,  6.92996958e+02,  6.72851277e+01])

In [47]:
len(lasso.coef_)

11

In [48]:
X[:, 10]

IndexError: index 10 is out of bounds for axis 1 with size 10

In [61]:
X.shape

(442, 10)

In [88]:
lasso.predict(X)

ValueError: shapes (442,10) and (11,) not aligned: 10 (dim 1) != 11 (dim 0)

In [89]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [90]:
lasso.predict(np.insert(X, 0, 1, axis=1))

array([67296.63503417, 67159.26319443, 67267.3975765 , 67256.90557491,
       67219.18697412, 67197.04003292, 67166.09561092, 67210.74953624,
       67250.14937633, 67304.62074993, 67189.00736268, 67188.0339994 ,
       67205.84713639, 67254.96131975, 67193.52793742, 67266.77693449,
       67301.71826072, 67273.74658386, 67238.48855   , 67214.49332475,
       67210.7932029 , 67177.93338239, 67205.192846  , 67348.38676129,
       67255.73206635, 67237.96221595, 67187.71873932, 67269.57843508,
       67219.9735552 , 67275.41321648, 67249.7316632 , 67160.46171492,
       67350.30327001, 67201.73210809, 67169.9396268 , 67177.30497612,
       67298.52997432, 67247.87052006, 67331.94436988, 67227.74814585,
       67244.36177902, 67164.70929027, 67236.0003818 , 67168.81644939,
       67310.92118856, 67215.90983467, 67232.91282851, 67199.9142715 ,
       67165.29403286, 67279.50622469, 67248.8324639 , 67259.97776987,
       67224.78284957, 67248.32189263, 67230.35176318, 67163.51392095,
      